"""init

Revision ID: d11084f222e2
Revises: a8f6a1e2f353
Create Date: 2026-05-14 16:01:22.328151

"""

import warnings
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import mysql
try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = 'd11084f222e2'
down_revision = 'a8f6a1e2f353'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_users_email'))
        batch_op.drop_index(batch_op.f('uq_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False, comment='用戶名'),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True, comment='電子郵箱'),
    sa.Column('description', mysql.VARCHAR(length=64), nullable=True, comment='描述'),
    sa.Column('phone', mysql.VARCHAR(length=64), nullable=True, comment='電話號碼'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否啟用'),
    sa.Column('dob', sa.DATE(), nullable=True, comment='出生日期'),
    sa.Column('address', mysql.VARCHAR(length=64), nullable=True, comment='地址'),
    sa.Column('sa_orm_sentinel', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('uq_users_email'), ['email'], unique=True)

    op.create_table('posts',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False, comment='作者（使用者 ID）'),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True, comment='帖子標題'),
    sa.Column('content', mysql.TEXT(), nullable=True, comment='帖子內容'),
    sa.Column('is_publish', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否發佈'),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True, comment='帖子描述'),
    sa.Column('sa_orm_sentinel', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
