from uuid import UUID
from pydantic import BaseModel, Field
from app.core.base_schema import BaseSchema


class {pascal_name}Base(BaseSchema): ...

class {pascal_name}Create(BaseModel): ...

class {pascal_name}Update(BaseModel): ...

class {pascal_name}Read({pascal_name}Base): ...